### ISSUE TITLE
Patch does not work when targetObjectRef points to Kubernetes Custom Resource

### ISSUE THREAD

**Issue by morningspace** [redhat-cop/resource-locker-operator#63]
I'm using resource-locker-operator w/ Argo CD to patch resources in GitOps. However, when targetObjectRef points to Kubernetes Custom Resource, the patch doesn't work. Here is an example:
 
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: test-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: test-patch
    patchTemplate: |
      metadata:
        annotations:
          foo: bar
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: somedomain.com/v1alpha1
      kind: MyType
      name: my-instance
      namespace: default
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
```

This is supposed to add the annotation to MyType/my-instance, but I don't see it happens. And there is an error in logs:

```console
2021-12-18T12:20:15.997Z	ERROR	patch-reconciler.resource-locker-operator/test-resource-locker.test-patch	unable to apply 	{"patch": {}, "on target": ... }, "error": "the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/redhat-cop/operator-utils/pkg/util/lockedresourcecontroller.(*LockedPatchReconciler).Reconcile
	/go/pkg/mod/github.com/redhat-cop/operator-utils@v1.1.4/pkg/util/lockedresourcecontroller/patch-reconciler.go:246
```

**Comment by morningspace** [comment]
Did quick look at the code, and issue happens at [this line](https://github.com/redhat-cop/operator-utils/blob/26a9d4efe6c40ed22f302342196ea6afc8b63170/pkg/util/lockedresourcecontroller/patch-reconciler.go#L246). It looks the `patch` variable should have been non-empty, but that's not true, and this points to [the line](https://github.com/redhat-cop/operator-utils/blob/26a9d4efe6c40ed22f302342196ea6afc8b63170/pkg/util/lockedresourcecontroller/patch-reconciler.go#L228) above that, which means `b bytes.Buffer` is empty.

I know that I didn't specify `sourceObjectRefs`, so `sourceMaps` is empty, but this should not be a problem, since when I try that w/ a builtin Kubernetes resource, such as ServiceAccount, it works. For example, below snippet works.

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: test-resource-locker
  namespace: resource-locker-operator
spec:
  patches:
  - id: test-patch
    patchTemplate: |
      metadata:
        annotations:
          foo: bar
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: v1
      kind: ServiceAccount
      name: my-instance
      namespace: default
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
```

@raffaelespazzoli
